Repository PowerNukkitX/PowerNukkitX, pull requests merged in 2024-07, with the labels that each got.

#1656 fix(drop xp sculk and break other tools):
  src/main/java/cn/nukkit/block/BlockSculk.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Priority: Medium, Status: confirmed, Status: Awaiting Review

#1658 feat(GameRules):
  src/main/java/cn/nukkit/level/GameRule.java
  src/main/java/cn/nukkit/level/GameRules.java
  src/main/java/cn/nukkit/network/process/DataPacketManager.java
  src/main/java/cn/nukkit/network/process/processor/SettingsCommandProcessor.java
  src/main/java/cn/nukkit/network/protocol/PacketHandler.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/SettingsCommandPacket.java
  src/main/java/cn/nukkit/registry/PacketRegistry.java
Labels: Type: To Do, Priority: Low, Status: confirmed

#1660 Fix ServerProperties and Clear Console
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/config/ServerProperties.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/resources/language/bra/lang.json
  src/main/resources/language/chs/lang.json
  src/main/resources/language/cht/lang.json
  src/main/resources/language/cze/lang.json
  src/main/resources/language/deu/lang.json
  src/main/resources/language/eng/lang.json
  src/main/resources/language/fin/lang.json
  src/main/resources/language/fra/lang.json
  src/main/resources/language/idn/lang.json
  src/main/resources/language/jpn/lang.json
  src/main/resources/language/kor/lang.json
  src/main/resources/language/ltu/lang.json
  src/main/resources/language/pol/lang.json
  src/main/resources/language/rus/lang.json
  src/main/resources/language/spa/lang.json
  src/main/resources/language/tur/lang.json
  src/main/resources/language/ukr/lang.json
  src/main/resources/language/vie/lang.json
Labels: Type: Fix, Priority: High, Status: confirmed, Status: Awaiting Review

#1664 fix(ServerProperties): the world seed asks for a Long parameter, but …
  src/main/java/cn/nukkit/config/ServerProperties.java
Labels: Priority: High, Status: confirmed, Status: Awaiting Review

#1662 fix: few bugs
  src/main/java/cn/nukkit/block/BlockCropsStem.java
  src/main/java/cn/nukkit/block/BlockDoublePlant.java
  src/main/java/cn/nukkit/block/BlockRedstoneOre.java
  src/main/java/cn/nukkit/entity/passive/EntityHorse.java
  src/main/java/cn/nukkit/entity/passive/EntityRabbit.java
  src/main/java/cn/nukkit/network/process/processor/InventoryTransactionProcessor.java
Labels: Type: Fix, Priority: Low, Status: confirmed
