Repository PowerNukkitX/PowerNukkitX, pull requests merged in 2024-09, with the labels that each got.

#1695 Fix: Reduce xp for anvil
  src/main/java/cn/nukkit/inventory/request/CraftRecipeOptionalProcessor.java
Labels: Type: Fix, Priority: Medium, Status: confirmed

#1697 fix: chests no longer split between chunks
  .run/PNX.run.xml
  src/main/java/cn/nukkit/blockentity/BlockEntityChest.java
Labels: Type: Fix, Priority: High, Status: confirmed

#1703 Rails connection
  src/main/java/cn/nukkit/block/BlockRail.java
Labels: Type: Fix, Priority: Low, Status: Awaiting Review
